image: ruby:2.5

pipelines:
  default:
    - step:
        name: Generate the blog with Jekyll
        deployment: production
        script:
          - bundle install
          - bundle exec jekyll build --destination public --trace
          - git config --global user.email "ilya.malinovsky@gmail.com"
          - git config --global user.name "Ilya Malinovsky"
          - git clone https://$BB_AUTH_STRING@bitbucket.org/imalinovsky/imalinovsky.bitbucket.io.git
          - cp -r public/* imalinovsky.bitbucket.io
          - cd imalinovsky.bitbucket.io
          - git add .
          - git commit -m "Updating changes.txt with latest build number."
          - git push https://$BB_AUTH_STRING@bitbucket.org/imalinovsky/imalinovsky.bitbucket.io.git
