name: Check Spelling (JS, Vue, HTML, Markdown, Text)

on: [pull_request, push]

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spelling
      uses: .github/actions/check-spelling.yml
      with:
        who-to-greet: 'Miki'
