name: Check Spelling (JS, Vue, HTML, Markdown, Text)

on: [pull_request, push]

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build Jekyll site
      run: bundle exec jekyll build
      shell: bash
    - name: Set input text
      id: set_text
      run: |
        content=$(cat _site/index.html)
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}" 
        echo $content
        echo "::set-env name=text::$content"
      shell: bash
    - name: Check spelling
      uses: mpokryva/spell-check-action@v1
