name: Check Spelling (JS, Vue, HTML, Markdown, Text)
 
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: UnicornGlobal/spellcheck-github-actions@0.4.0
